<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="BLLCLAPUS1698" failures="1" tests="4" name="MessageUtil" time="0.062" errors="0" timestamp="2022-02-16T14:00:12 PST">
  <testcase classname="AllTests" name="subAdd" time="0.008"/>
  <testcase classname="AllTests" name="testAdd" time="0.001"/>
  <testcase classname="GroupTestExample" name="testPrintMessage" time="0.001"/>
  <testcase classname="GroupTestExample" name="testingExitMessage" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [www..com] but found [www.mywebsite.com]">
      <![CDATA[java.lang.AssertionError: expected [www..com] but found [www.mywebsite.com]
at GroupTestExample.testingExitMessage(GroupTestExample.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testingExitMessage -->
  <testcase classname="AllTests" name="printAdd" time="0.0">
    <ignored/>
  </testcase> <!-- printAdd -->
  <testcase classname="GroupTestExample" name="testSalutationMessage" time="0.0">
    <ignored/>
  </testcase> <!-- testSalutationMessage -->
</testsuite> <!-- MessageUtil -->
